website/call/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^scripts/$', views.scripts, name='scripts'),
]

website/website/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from website import settings

if settings.DEBUG:
    urlpatterns = [
        url(r'^admin/', admin.site.urls),
    ]
else:
    urlpatterns = []

urlpatterns += [
    url(r'', include('call.urls', namespace='call')),
]

website/call/models.py
from django.db import models

class GetOrNoneManager(models.Manager):
    """Adds get_or_none method to objects
    """
    def get_or_none(self, **kwargs):
        try:
            return self.get(**kwargs)
        except self.model.DoesNotExist:
            return None

class Campaign(models.Model):
    name = models.CharField(max_length=20, unique=True)
    hashtag = models.CharField(max_length=100)
    action = models.TextField(default=None, blank=True, null=True)
    checker = models.CharField(max_length=100, default=None, blank=True, null=True)
    include_senators = models.BooleanField(default=True)
    include_representatives = models.BooleanField(default=True)

    def __str__(self):
        return self.name

class Position(models.Model):
    HAS_NOT_SAID = 'N'
    SUPPORTS = 'S'
    DENOUNCES = 'D'

    politician = models.ForeignKey('Politician')
    campaign = models.ForeignKey('Campaign')
    position = models.CharField(max_length=1,
                                choices=[(HAS_NOT_SAID, 'Has not said'),
                                         (SUPPORTS,     'Supports'    ),
                                         (DENOUNCES,    'Denounces'   )],
                                default=HAS_NOT_SAID)
    script = models.TextField(default=None, blank=True)

    def __str__(self):
        return '%s: %s %s' % (self.politician, self.position, self.campaign)

class Politician(models.Model):
    objects = GetOrNoneManager()

    HOUSE = 'H'
    SENATE = 'S'

    zip_or_state = models.CharField(max_length=5)
    district_or_class = models.PositiveSmallIntegerField()
    chamber = models.CharField(max_length=1,
                               choices=[(HOUSE, 'House of Representatives'),
                                        (SENATE, 'Senate')])
    leadership_role = models.CharField(max_length=255, blank=True)
    shown_to_all = models.ManyToManyField(Campaign, blank=True)

    def __str__(self):
        return '%s-%s %s' % (self.zip_or_state, self.district_or_class, self.chamber)

class Phone(models.Model):
    number = models.CharField(max_length=10)
    desc = models.TextField()
    politician = models.ForeignKey('Politician')

    def __str__(self):
        return '%s: (%s) %s-%s' % (self.desc, self.number[0:3], self.number[3:6], self.number[6:])

website/call/views.py
from website import settings
from collections import namedtuple
from enum import Enum
from itertools import chain
from django.http import Http404
from django.template import Template, Context
from django.template.loader import get_template
from django.shortcuts import render, HttpResponse
from call import scrape
from call.constants import STATE_NAMES, THE_STATES
from call.models import Politician, Campaign, Position

def get_campaign(request):
    c = request.GET.get('campaign')
    if c is None and settings.CAMPAIGN_OVERRIDE is not None:
        c = settings.CAMPAIGN_OVERRIDE
    if c is None or c == '':
        if 'bannon' in request.get_host():
            c = 'bannon'
        elif 'pruitt' in request.get_host():
            c = 'pruitt'
        elif 'aca' in request.get_host():
            c = 'obamacare'
        elif 'neveragain' in request.get_host():
            c = 'neveragain'
        else:
            return None
    return Campaign.objects.get(name=c)

def index(request):
    return render_index(request, {})

def render_index(request, extra_values):
    values = {'campaign':  get_campaign(request),
              'campaigns': Campaign.objects.all(),
              'zip':       '',
              'name':      '' }
    values.update(extra_values)
    return render(request, 'call/index.html', values)

Phone = namedtuple('Phone',
                   ['number', 'desc'])

Critter = namedtuple('Critter',
                     ['title', 'name', 'last_name', 'leadership_role',
                      'party', 'state',
                      'phones',
                      'position', 'script'])

def merge_scraped_with_model(scraped_critter, model_pol, positions, campaign):
    if model_pol:
        try:
            model_pos = Position.objects.get(politician=model_pol, campaign__name=campaign)
            script          = model_pos.script          or None
            position        = model_pos.position
        except Position.DoesNotExist:
            script          = None
            position        = None

        extra_phones        = [Phone(number = p.number, desc = p.desc) for p in model_pol.phone_set.all()]
        leadership_role     = model_pol.leadership_role or None
    else:
        extra_phones    = []
        position        = None
        script          = None
        leadership_role = None
    
    title  = 'Representative' if scraped_critter.chamber == Politician.HOUSE else 'Senator'
    phones = [Phone(number = scraped_critter.dc_phone, desc = 'DC office')] + extra_phones

    if not position:
        position = Position.HAS_NOT_SAID
        try:
            if positions[scraped_critter.website]:
                position = Position.DENOUNCES
        except KeyError:
            try:
                if positions[scraped_critter.dc_phone]:
                    position = Position.DENOUNCES
            except KeyError:
                pass
    
    return Critter(title           = title,
                   name            = scraped_critter.name,
                   last_name       = scraped_critter.last_name,
                   leadership_role = leadership_role,
                   party           = scraped_critter.party,
                   state           = scraped_critter.state,
                   phones          = phones,
                   position        = position,
                   script          = script)

def from_scraped(zip_or_state, critter, positions, campaign):
    matching = Politician.objects.get_or_none(chamber           = critter.chamber,
                                              zip_or_state      = zip_or_state,
                                              district_or_class = critter.disambig)
    return merge_scraped_with_model(critter, matching, positions, campaign)

def from_model(pol, positions, campaign):
    get = scrape.get_representatives if pol.chamber == Politician.HOUSE else scrape.get_senators
    matching = next(filter(lambda r: r.disambig == pol.district_or_class,
                           get(pol.zip_or_state)))
    return merge_scraped_with_model(matching, pol, positions, campaign)

def render_script(critter, context, campaign):
    if critter.script:
        script = Template(critter.script)
    elif critter.position == Position.HAS_NOT_SAID:
        script = get_template('call/%s/has_not_said.html' % campaign)
    elif critter.position == Position.SUPPORTS:
        script = get_template('call/%s/supports.html' % campaign)
    elif critter.position == Position.DENOUNCES:
        script = get_template('call/%s/denounces.html' % campaign)
    
    context['critter'] = critter
    context['campaign'] = campaign

    return script.render(Context(context))

def scripts(request):
    campaign = get_campaign(request)
    if campaign is None:
        return render_index(request, {
            'zip': request.GET.get('zip', ''),
            'name': request.GET.get('name', ''),
            'error': 'You have to choose an issue'
            })

    name = request.GET.get('name', '$NAME')
    if len(name) == 0:
        name = '$NAME'
    zipcode = request.GET['zip']

    try:
        (city, state) = scrape.zip_code_city_state(zipcode)
    except AttributeError:
        return render_index(request, {
                'zip': zipcode,
                'name': request.GET.get('name', ''),
                'error': 'Invalid zip code %s' % zipcode
                })

    if campaign.checker is None or campaign.checker == '':
        positions = {}
    else:
        positions = getattr(scrape, campaign.checker)(state)

    if campaign.include_senators:
        sens  = (from_scraped(state,   s, positions, campaign) for s in scrape.get_senators(state))
    else:
        sens = []
    gsens = (from_model(s, {}, campaign) for s in Politician.objects.filter(shown_to_all=campaign, chamber=Politician.SENATE))
    greps = (from_model(r, {}, campaign) for r in Politician.objects.filter(shown_to_all=campaign, chamber=Politician.HOUSE))
    if campaign.include_representatives:
        reps  = (from_scraped(zipcode, r, positions, campaign) for r in scrape.get_representatives(zipcode))
    else:
        reps = []

    def render_with(place):
        return lambda c: c._replace(script = render_script(c, {'name': name, 'place': place}, campaign))

    state_name = STATE_NAMES[state]
    if state_name in THE_STATES:
        state_name = 'the %s' % state_name

    good_critters = []
    bad_critters  = []
    for critter in chain(map(render_with(city),       chain(reps, sens)),
                         map(render_with(state_name), chain(greps, gsens))):
        if critter.position == Position.DENOUNCES:
            good_critters.append(critter)
        else:
            bad_critters.append(critter)
    
    return render(request, 'call/scripts.html',
                  { 'campaign':      campaign,
                    'state':         state,
                    'good_critters': good_critters,
                    'bad_critters':  bad_critters })

website/call/templates/call/critters_scripts.html
{% load app_filters %}

{% for critter in critters %}
    <h1 id="script-for-{{critter.name|slugify}}" class="{{critter.position|position_class}}">Script for {{critter.last_name}}</h1>
    {{critter.script|safe}}
{% endfor %}

website/call/templates/call/header.html
{% load staticfiles %}

<meta charset="utf-8">
<meta name="generator" content="pandoc">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<link rel="stylesheet" href="{% static "killercup-pandoc.css" %}">

<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.min.js"></script>
<![endif]-->

<!-- generated by realfavicongenerator.net -->
<link rel="apple-touch-icon" sizes="152x152" href="/static/favicons/apple-touch-icon.png">
<link rel="icon" type="image/png" href="/static/favicons/favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="/static/favicons/favicon-16x16.png" sizes="16x16">
<link rel="manifest" href="/static/favicons/manifest.json">
<link rel="mask-icon" href="/static/favicons/safari-pinned-tab.svg" color="#5bbad5">
<link rel="shortcut icon" href="/static/favicons/favicon.ico">
<meta name="apple-mobile-web-app-title" content="GovDial">
<meta name="application-name" content="GovDial">
<meta name="msapplication-config" content="/static/favicons/browserconfig.xml">
<meta name="theme-color" content="#ffffff">

website/call/templates/call/index.html
<!DOCTYPE html>
<html>
    <head>
        {% if campaign %}
            <title>Call your reps to #{{ campaign.hashtag }}</title>
        {% else %}
            <title>Call your reps to #Resist</title>
        {% endif %}
        {% include "call/header.html" %}
    </head>
    <body>
        <div align="center">
            <form action="{% url 'call:scripts' %}" method="get">
                <h2>What do you care about?</h2>
                <select class="big" name="campaign">
                    <option value="">Choose one</option>
                    {% for c in campaigns %}
                        <option
                            {% if c == campaign %}selected{% endif %}
                            value="{{ c.name }}"
                            >
                            #{{ c.hashtag }}
                        </option>
                    {% endfor %}
                </select>
                <h2>Where do you live?</h2>
                <table>
                    <tr>
                        <td>
                            <label for="zip">ZIP code:</label>
                        </td>
                        <td>
                            <input type="text" name="zip" id="zip" value="{{zip}}" />
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label for="name">(Optional) First name:</label>
                        </td>
                        <td>
                            <input type="text" name="name" id="name" value="{{name}}" />
                        </td>
                    </tr>
                </table>
                <input class="big" type="submit" value="Find my reps!" />
            </form>
            {% if error %}
                <p style="color: orangered">
                    {{error}}
                </p>
            {% endif %}
        </div>
    </body>
</html>

website/call/templates/call/phone_numbers.html
{% load app_filters %}
{% load humanize %}

{% for critter in critters %}
    {% for phone in critter.phones %}
        <li class="{{critter.position|position_class}}">
          {{critter.title|slice:":3"}}.
          {{critter.name}}{% if critter.leadership_role %}, {{critter.leadership_role}}{% endif %}
          ({{critter.party|slice:":1"}}-{{critter.state}}{% if critter.chamber == 'H' %} {{ critter.disambig|ordinal }}{% endif %}){% if phone.desc %}, {{phone.desc}}{% endif %}:
          ({{phone.number|slice:":3"}}) {{phone.number|slice:"3:6"}}-{{phone.number|slice:"6:"}}
        </li>
    {% endfor %}
{% endfor %}

website/call/templates/call/scripts.html
{% load app_filters %}
{% load staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <title>Call your reps to #{{ campaign.hashtag }}</title>
        {% include "call/header.html" %}
        <link rel="stylesheet" href="{% static "stances.css" %}">
    </head>
    <body>
        <h1 id="phone-numbers">Phone numbers</h1>
        <ul>
            {% include "call/phone_numbers.html" with critters=bad_critters %}
            {% if bad_critters and good_critters %}
                <li class="announcement separator">
                    These legislators have already {{ campaign.action|safe }}
                </li>
            {% elif good_critters %}
                <li class="announcement">
                    All your representatives have already {{ campaign.action }}!
                </li>
            {% endif %}
            {% include "call/phone_numbers.html" with critters=good_critters %}
        </ul>

        {% include "call/critters_scripts.html" with critters=bad_critters %}
        {% if good_critters %}
            <h1 id="call-and-thank" class="announcement">
                If you’d like to call and thank your representatives who did the
                right thing (calling once is enough!)…
            </h1>
        {% endif %}
        {% include "call/critters_scripts.html" with critters=good_critters %}

        <h1 id="some-resources">Some resources</h1>
        <ul>
            {% if campaign.name == 'bannon' %}
                <li>
                    <a href="http://thehill.com/policy/national-security/316764-susan-rice-trumps-nsc-order-stone-cold-crazy">“Susan Rice: Trump's National Security Council order ‘stone cold crazy’”</a>,
                    by Rebecca Savransky for
                    <a href="http://www.thehill.com/">The Hill</a>
                </li>
                <li>
                    <a href="https://www.splcenter.org/stephen-bannon-has-no-business-white-house">“Stephen Bannon has no business in the White House”</a>,
                    by the
                    <a href="https://www.splcenter.org/">Southern Poverty Law Center</a>
                </li>
                <li>
                    <a href="http://www.nytimes.com/2016/11/15/us/politics/stephen-bannon-breitbart-words.html">“Stephen Bannon and Breitbart News, in Their Words”</a>,
                    by Daniel Victor and Liam Stack for
                    <a href="http://www.nytimes.com/">The New York Times</a>
                </li>
                <li>
                    <a href="https://www.reddit.com/r/NeutralPolitics/comments/5d33ad/who_is_stephen_bannon_and_why_is_he_accused_of/">“Who is Stephen Bannon and why is he accused of racism?”</a>,
                    a thread on
                    <a href="https://www.reddit.com/r/NeutralPolitics">/r/NeutralPolitics</a>
                </li>
                <li>
                    <a href="http://www.snopes.com/2016/11/14/steve-bannon-accused-of-having-white-supremacist-views/">“Steve Bannon Accused of Having White Supremacist Views”</a>,
                    by Bethania Palma for
                    <a href="http://www.snopes.com/">Snopes</a>
                </li>
                <li>
                    <a href="http://www.dailywire.com/news/8441/i-know-trumps-new-campaign-chairman-steve-bannon-ben-shapiro">“I Know Trump’s New Campaign Chairman, Steve Bannon.  Here’s What You Need To Know.”</a>,
                    by Ben Shapiro (former Breitbart editor-at-large) for
                    <a href="http://www.dailywire.com/">The Daily Wire</a>
                </li>
                <li>
                    <a href="http://www.motherjones.com/kevin-drum/2016/11/steve-bannon-racist-lets-find-out">“Is Steve Bannon Racist? Let’s Find Out!”</a>,
                    by Kevin Drum for
                    <a href="http://www.motherjones.com/">Mother Jones</a>
                </li>
                <li>
                    <a href="https://docs.google.com/document/d/1VSLq_eUnL3RBZ3fOAS3SW3XStusuUdAipDbW--ZqbVs/edit?usp=sharing">“Opposition to Bannon Is Bipartisan: Republican opposition to Bannon”</a>,
                    a crowdsourced document
                </li>
            {% elif campaign.name == 'pruitt' %}
                <li>
                    <a href="https://theintercept.com/2016/12/07/donald-trumps-epa-team-will-be-run-by-fossil-fuel-industry-advocates/">“Donald Trump’s EPA Team Will Be Run by Fossil-Fuel Industry Advocates”</a>
                    by Lee Fang and Naomi LaChance for
                    <a href="https://theintercept.com/">The Intercept</a>
                </li>
                <li>
                    <a href="http://www.nytimes.com/2016/12/07/us/politics/scott-pruitt-epa-trump.html">“Trump Picks Scott Pruitt, Climate Change Denialist, to Lead E.P.A.”</a>
                    by Coral Davenport and Eric Lipton for
                    <a href="http://www.nytimes.com/">The New York Times</a>
                </li>
                <li>
                    <a href="http://www.wsj.com/articles/donald-trump-taps-oklahoma-attorney-general-scott-pruitt-to-lead-epa-1481143068">“Donald Trump Taps Oklahoma Attorney General Scott Pruitt to Lead EPA”</a>
                    by Amy Harder and Peter Nicholas for
                    <a href="http://www.wsj.com">The Wall Street Journal</a>
                </li>
                <li>
                    <a href="http://www.businessinsider.com/sierra-club-scott-pruitt-epa-arsonist-fighting-fires-2016-12">“One of the oldest environmental groups in the US says Trump’s EPA pick is ‘like putting an arsonist in charge of fighting fires’”</a>
                    by Rafi Letzter for
                    <a href="http://www.businessinsider.org">Business Insider</a> (quoting the <a href="http://sierraclub.org">Sierra Club</a>)
                </li>
                <li>
                    <a href="http://www.audubon.org/news/audubon-deeply-concerned-anti-epa-nominee-scott-pruitt">“Audubon Deeply Concerned by ‘Anti-EPA’ Nominee Scott Pruitt”</a>
                    by the
                    <a href="http://www.audubon.org">National Audubon Society</a>
                </li>
                <li>
                    <a href="https://www.wired.com/2015/01/senators-dont-believe-human-caused-climate-change/">“Here Are All the Senators Who Do and Don’t Believe in Human-Caused Climate Change”</a>
                    by Victoria Tang for
                    <a href="https://www.wired.com">Wired</a>
                </li>
            {% elif campaign.name == 'obamacare' %}
                <li>
                    <a href="https://www.bostonglobe.com/opinion/editorials/2017/01/09/the-reality-repealing-affordable-care-act/neZNjqiXjUSgO7unvEA57M/story.html">“The reality of repealing the Affordable Care Act”</a>
                    by Sylvia Mathews Burwell for the
                    <a href="https://www.bostonglobe.com">Boston Globe</a>
                </li>
                <li>
                    <a href="https://www.washingtonpost.com/powerpost/anxious-lawmakers-to-gop-leaders-whats-the-plan-to-replace-obamacare/2017/01/12/bdbea6bc-d8e1-11e6-9a36-1d296534b31e_story.html">“Anxious lawmakers to GOP leaders: What's the plan to replace ACA?”</a>
                    by Mike DeBonis for the
                    <a href="https://www.washingtonpost.com">Washington Post</a>
                </li>
                <li>
                    <a href="https://drive.google.com/file/d/0B5610UO7UfrodXRmdERtTE5ZLWM/view">“Repealing the Affordable Care Act Threatens Millions of Americans”</a>,
                    fact sheet from the
                    <a href="https://www.clinicianaction.org/">Clinician Action Network</a>
                </li>
                <li>
                    <a href="http://www.cbpp.org/research/health/impact-of-affordable-care-act-repeal">“Impact of Affordable Care Act Repeal”</a> (jump to <a href="http://www.cbpp.org/sites/default/files/atoms/files/12-7-16health-factsheets-{{ state|lower }}.pdf">{{ state }}</a>),
                    state-by-state fact sheet from the
                    <a href="http://www.cbpp.org/">Center on Budget Policy and Priorities</a>
                </li>
            {% elif campaign.name == 'neveragain' %}
                <li>
                    <a href="http://www.latimes.com/nation/la-na-pol-refugee-policy-20170128-story.html">“Trump’s ban on some U.S. entries sparks confusion and protest worldwide, and legal rebukes at home”</a>,
                    by Laura King, Barbara Demick and Molly Hennessy-Fiske for the
                    <a href="http://www.latimes.com/">Los Angeles Times</a>
                </li>
                <li>
                    <a href="http://www.npr.org/sections/thetwo-way/2017/01/28/512158238/arrivals-to-u-s-blocked-and-detained-as-trumps-immigration-freeze-sets-in">“Federal Judge Stays Deportations, Blocking Part Of Trump’s Immigration Order”</a>,
                    by Maquita Peters and Colin Dwyer for
                    <a href="http://www.npr.org/">National Public Radio</a>
                </li>
                <li>
                    <a href="https://www.cato.org/blog/little-national-security-benefit-trumps-executive-order-immigration">“Little National Security Benefit to Trump’s Executive Order on Immigration”</a>,
                    by Alex Nowrasteh for the
                    <a href="https://www.cato.org/">Cato Institute</a>
                </li>
            {% endif %}
        </ul>
        <h1></h1>
        <h3 id="congressional-contact-information">This didn’t work for you?<br/>Here’s all the congressional contact information!</h3>
        <ul>
            <li><a href="http://www.senate.gov/general/contact_information/senators_cfm.cfm">Senate</a></li>
            <li><a href="http://clerk.house.gov/member_info/mcapdir.aspx">House of Representatives</a></li>
            <li><a href="http://www.house.gov/representatives/find/">Find your representative</a></li>
        </ul>
    </body>
</html>